### PR TITLE
Fixes to the docs theme

### LINKED ISSUE #13: use MDA doc style for docs
The documentation at https://www.mdanalysis.org/hole2-mdakit/ still has RTD style. But we prefer any docs hosted by ourselves to follow our standard style.

IIRC, this is mainly achieved by copying one or two style files.

### LINKED ISSUE #24: Documentation does not link to itself on the landing page
Documentation says that the documentation is hosted on RTD (which it is not) and the link fails 404s. Update the link.

### PR DESCRIPTION
**Pull request by ianmkenney**
- Added msmb_theme dependency in workflow
- Added sphinx_rtd_theme to requirements.yaml
- Added new custom.css and MDA logos
- Updated conf.py

Fixes #13

### CODE REVIEW

**Comment by orbeckst** [comment]
Can you link to a PR build on RTD so that I can check visually? We _should_ be doing such a build for each PR but I cannot set it under checks.

**Comment by ianmkenney** [comment]
@orbeckst we're using github pages, I'm not quite sure how to show the outputs of those builds on PRs, I might have to revisit this later then

**Comment by orbeckst** [comment]
Yes, but for other projects (see MDA, for example, possibly also gridDataFormats) we are also building a RTD to preview docs. I had thought we did this here as well. It probably just needs enabling RTD and enabling a hook in RTD… but I don’t remember details. Am 7/14/23 um 12:00 schrieb Ian Kenney ***@***.***>:﻿
@orbeckst we're using github pages

**Comment by ianmkenney** [comment]
@orbeckst Alright, docs are building, see https://mdakithole2--23.org.readthedocs.build/en/23/

**Review by orbeckst — APPROVED** [review]
Looks good & thanks for adding the RTD PR check.

**Pull request merged**
